server:
  port: 8002
  servlet:
    context-path: /intelligent


spring:
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 20MB
      location: /tmp/uploads #临时存放文件
  datasource:
    url: jdbc:mysql:///etoak?serverTimezone=UTC
    username: root
    password: etoak
    driver-class-name: com.mysql.cj.jdbc.Driver
mybatis-plus:
  mapper-locations: classpath:/mapper/*.xml  #扫描mapper文件
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl #开启日志输出
  type-aliases-package: com.intelligent.entity # 指定实体类所在的包路径
  global-config:
    db-config:
      id-type: auto # 主键策略，auto 表示自动生成。
      logic-delete-field: 0 # 逻辑未删除值(默认为 0)
      logic-delete-value: 1 # 逻辑已删除值(默认为 1)
logging:
  level:
    com.intelligent.mapper: debug

# 阿里云OSS配置
aliyun:
  oss:
    end-point: http://oss-sd-1-a.ops-sgmc.sd.sgcc.com.cn/
    access-key-id: 9Gq9WM6rObpbvh3V
    access-key-secret: UUPdTnIY60J93xIbZlGaYT5LFZAmIA
    bucket-name: zhdlqx

